name: Generate League Scripts

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose up --build
        env:
          GDRIVE_JSON_URL: ${{ secrets.GDRIVE_JSON_URL }}
          GDRIVE_BUILDER_URL: ${{ secrets.GDRIVE_BUILDER_URL }}

      - name: Upload generated league scripts
        uses: actions/upload-artifact@v4
        with:
          name: league-scripts
          path: app/data/temp/leagues/